# User needs to:
#   - provide the quarkus:oidc configuration
#   - provide the following environment variables:
#       QUARKUS_DATASOURCE_PASSWORD, QUARKUS_MINIO_ACCESS_KEY, QUARKUS_MINIO_SECRET_KEY,
#       QUARKUS_REDIS_CHAT_MEMORY_PASSWORD, QUARKUS_REDIS_HISTORY_PASSWORD, QUARKUS_OIDC_CREDENTIALS_SECRET=${OIDC_CREDENTIALS_SECRET}
#     and with default model config: OPENAI_API_KEY

# Default configuration for Docker:
quarkus:
  # Configure JDBC datasource (https://quarkus.io/guides/datasource#datasource-reference)
  datasource:
    db-kind: postgresql
    username: llamara
    jdbc:
      url: jdbc:postgresql://postgres:5432/llamara
      driver: org.postgresql.Driver
  hibernate-orm:
    database:
      generation: validate

  # Configure Minio client for file storage
  # You need to provide QUARKUS_MINIO_ACCESS_KEY and QUARKUS_MINIO_SECRET_KEY environment variables
  minio:
    url: http://minio
    port: 9000
    secure: false

  # Configure Redis client for chat memory & history
  redis:
    chat-memory:
      hosts: redis://redis:6379/1
    chat-history:
      hosts: redis://redis:6379/2
