# User needs to:
#   - provide the quarkus:oidc configuration
#   - provide the following environment variables:
#       QUARKUS_DATASOURCE_PASSWORD, MINIO_ACCESS_KEY, MINIO_SECRET_KEY,
#       QUARKUS_REDIS_CHAT_MEMORY_PASSWORD, QUARKUS_REDIS_HISTORY_PASSWORD, QUARKUS_OIDC_CREDENTIALS_SECRET=${OIDC_CREDENTIALS_SECRET}
#     and with default model config: OPENAI_API_KEY

# Default configuration for Docker:
embedding:
  store:
    type: qdrant # Supported types: qdrant
    host: qdrant
    port: 6334 # Qdrant gRPC port
    tls: false
    collection-name: text-embedding-3-large
    vector-size: 3072

file-storage:
  type: minio
  url: http://minio
  port: 9000
  # Make sure that UID 185 has write access to this path when mounting it as volume
  path: /data/knowledge

quarkus:
  # Configure JDBC datasource (https://quarkus.io/guides/datasource#datasource-reference)
  datasource:
    db-kind: postgresql
    username: llamara
    jdbc:
      url: jdbc:postgresql://postgres:5432/llamara
      driver: org.postgresql.Driver
  hibernate-orm:
    schema-management:
      strategy: validate

  # Configure Redis client for chat memory & history
  redis:
    chat-memory:
      hosts: redis://redis:6379/1
    chat-history:
      hosts: redis://redis:6379/2
