file-storage:
  # You need to provide MINIO_ACCESS_KEY and MINIO_SECRET_KEY environment variables
  type: minio
  url: http://localhost
  port: 9000

quarkus:
  # Configure OIDC provider
  oidc:
    auth-server-url: http://localhost:8180/realms/llamara
    client-id: llamara-backend

  # Configure JDBC datasource (https://quarkus.io/guides/datasource#datasource-reference)
  datasource:
    db-kind: postgresql
    username: llamara
    jdbc:
      url: jdbc:postgresql://localhost:5432/llamara
      driver: org.postgresql.Driver
  hibernate-orm:
    schema-management:
      strategy: validate

  # Configure Redis client for chat memory & history
  redis:
    chat-memory:
      hosts: redis://localhost:6379/1
    chat-history:
      hosts: redis://localhost:6379/2
