embedding:
  store:
    type: qdrant # Supported types: qdrant
    host: localhost
    port: 6334 # Qdrant gRPC port
    tls: false

file-storage:
  type: minio
  url: http://localhost
  port: 9000

MINIO_ACCESS_KEY: minioaccess
MINIO_SECRET_KEY: miniosecret

quarkus:
  swagger-ui:
    enable: true

  keycloak:
    devservices:
      enabled: true

  oidc:
    auth-server-url:
    client-id: backend-service
    credentials:
      secret: secret

  datasource:
    devservices:
      enabled: true
      port: 5432
    db-kind: postgresql
    jdbc:
      driver: org.postgresql.Driver
  hibernate-orm:
    database:
      generation: drop-and-create

  minio:
    devservices:
      enabled: true
      port: 9000
      shared: false
    url:

  redis:
    devservices:
      enabled: true
      port: 6379
    chat-memory:
      hosts: redis://localhost:6379/1
    chat-history:
      hosts: redis://localhost:6379/2

  langchain4j:
    qdrant:
      devservices:
        port: 6334
        shared: false
        qdrant-image-name: docker.io/qdrant/qdrant:v1.13.2-unprivileged
