name: "Maven Build"
inputs:
  java:
    description: "Java version (optional)"
    required: false
    default: "21"
  mvnw:
    description: "Path to maven wrapper (optional)"
    required: false
    default: "./mvnw"
  pom:
    description: "Path to the Maven POM file (optional)"
    required: false
    default: "pom.xml"
  command:
    description: "Maven build command (optional)"
    required: false
    default: "package"
  skip_spotless:
    description: "Skip Spotless check (optional)"
    required: false
    default: "false"
  skip_changed_files:
    description: "Skip changed files check (optional)"
    required: false
    default: "false"
  OPENAI_API_KEY:
    description: "OpenAI API Key (optional)"
    required: false
runs:
  using: "composite"
  steps:
    - name: Set up Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java }}

    - name: Run Spotless Check
      if: ${{ inputs.skip_spotless != 'true' }}
      shell: bash
      run: "${{ inputs.mvnw }} -B --show-version --file ${{ inputs.pom }} spotless:check"

    - name: Maven Build
      shell: bash
      run: "${{ inputs.mvnw }} -B --show-version --file ${{ inputs.pom }} ${{ inputs.command }}"
      env:
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY || 'sk-prod-key' }}

    - name: Verify Changed Files
      if: ${{ inputs.skip_changed_files != 'true' }}
      id: verify-changed-files
      shell: bash
      run: |
        set -o pipefail
        changed_files=$(echo -n "$(git diff --name-only HEAD && git ls-files --others --exclude-standard)"|tr '\n' ' ')
        echo "changed_files=$changed_files" >> $GITHUB_OUTPUT

    - name: Fail on Changed Files
      if: steps.verify-changed-files.outputs.changed_files != ''
      shell: bash
      env:
        CHANGED_FILES: ${{ steps.verify-changed-files.outputs.changed_files }}
      run: |
        echo "::error::Files have changed: $CHANGED_FILES"
        exit 1
