name: CI Build Docker

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/ci-build-docker.yaml'
      - 'src/main/docker/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/ci-build-docker.yaml'
      - 'src/main/docker/**'
  workflow_dispatch:

jobs:
  build-docker:
    strategy:
      matrix:
        os: [ 'ubuntu-24.04' ]
        java: [ '21' ]
        maven: [ '3.9.9' ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Maven Build
        uses: ./.github/actions/maven-build
        with:
          java: ${{ matrix.java }}
          maven: ${{ matrix.maven }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          push: false
          file: src/main/docker/Dockerfile.jvm
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
